name: qbittorrent-tak
summary: UnOfficial release of qBittorrent
description: |
  **qBittorrent is a free and open-source BitTorrent client** based on the Qt toolkit and libtorrent-rasterbar library.

  * The web interface is accessible by default at http://localhost:8080
  * See https://www.qbittorrent.org for more details.

  **qBittorrent Release 5+**
  * Service is restarted on any condition.

  **Post install commands required to access media folders and see default password :**

  sudo snap connect qbittorrent-tak:removable-media

  sudo snap logs qbittorrent-tak
website: https://www.qbittorrent.org
source-code: https://github.com/TehAppKiller/qbittorrent-tak
issues: https://github.com/TehAppKiller/qbittorrent-tak/issues
license: MIT
icon: icon.svg
grade: stable
confinement: strict
base: core24
adopt-info: qbittorrent
platforms:
  amd64:
  arm64:
  armhf:
  ppc64el:
  s390x:
  riscv64:

apps:
  qbittorrent:
    command: bin/run-qbittorrent.sh
    daemon: simple
    restart-condition: always
    plugs:
      - network
      - network-bind
      - removable-media
    environment:
      QT_PLUGIN_PATH: $SNAP/usr/plugins

parts:
  libtorrent:
    source: .
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
    build-packages:
      - curl
      - git
    override-pull: |
      craftctl default

      # Get Last Source Tag version
      src_version=$(git ls-remote --tags --sort='version:refname' https://github.com/arvidn/libtorrent.git | grep '\/v[0-9]*\.[0-9]*\.[0-9]*$' | tail -n 1 | sed 's/.*\/v//');

      rm -rf $CRAFT_PART_SRC/{,.[!.],..?}*
      git clone -b v$src_version --depth=1 --recurse-submodules https://github.com/arvidn/libtorrent.git .
    prime:
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libtorrent-rasterbar*

  qt6:
    after:
      - libtorrent
    source: .
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_LIBRARY_PATH=$CRAFT_ARCH_TRIPLET_BUILD_FOR
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DINSTALL_LIBDIR=lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR
      - -DINSTALL_INCLUDEDIR=include/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6
      - -DFEATURE_gui=OFF
      - -DFEATURE_widgets=OFF
      - -DFEATURE_dbus=OFF
      - -DQT_BUILD_TESTS=OFF
    build-packages:
      - curl
      - git
      - perl
    override-pull: |
      craftctl default

      # Get Last Source Tag version
      src_version=$(git ls-remote --tags --sort='version:refname' https://code.qt.io/qt/qt5.git | grep '\/v[0-9]*\.[0-9]*\.[0-9]*$' | tail -n 1 | sed 's/.*\/v//');

      rm -rf $CRAFT_PART_SRC/{,.[!.],..?}*
      git clone -b v$src_version --depth=1 https://code.qt.io/qt/qt5.git .
      perl init-repository --module-subset=qtbase,qttools
    prime:
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libQt6Core.so*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libQt6Network.so*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libQt6Sql.so*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libQt6Xml.so*
      - usr/plugins/tls

  qbittorrent:
    after:
      - qt6
    override-pull: |
      craftctl default

      # Get Last Source Tag version and Check Snap (with same Source) version
      src_version=$(git ls-remote --tags --sort='version:refname' https://github.com/qbittorrent/qBittorrent.git | grep 'release\-[0-9]*\.[0-9]*\.[0-9]*$' | tail -n 1 | sed 's/.*\/release-//');
      echo "Source last tag: ${src_version}"
      snap_last_version=$(curl -sL -H "Snap-Device-Series: 16" "https://api.snapcraft.io/v2/snaps/info/qbittorrent-tak?architecture=${CRAFT_ARCH_BUILD_FOR}&fields=version" | sed -nre "s/^.*\"stable\"\,\"track\"\:\"latest\"\}\,\"version\"\:\"([^\"]*)\".*/\1/p");
      echo "Snap last version: ${snap_last_version}"
      snap_build_with_same_version=$(echo $snap_last_version | sed -nre "s/^($src_version.*).*/\1/p");
      # Same version ?
      if [ -z "$snap_build_with_same_version" ]
      then
        new_snap_version="${src_version}";
      else
        # Get snap build version
        snap_build=$(echo $snap_build_with_same_version | sed -nre 's/^.*-v([0-9]*).*/\1/p');
        # Already a build version ?
        if [ -z "$snap_build" ]
        then
          # init @v2
          new_snap_build="2";
        else
          # increment @v+1
          new_snap_build=$(($snap_build+1));
        fi

        new_snap_version="${src_version}-v${new_snap_build}";
      fi

      craftctl set version=$new_snap_version

      # Pull
      rm -rf $CRAFT_PART_SRC/{,.[!.],..?}*
      git clone -b release-${src_version} --depth=1 https://github.com/qbittorrent/qBittorrent.git .
    source: .
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=RelWithDebInfo
      - -DGUI=OFF
    build-packages:
      - curl
      - git
    override-prime: |
      craftctl default
      chmod +rx $CRAFT_PRIME/bin/run-qbittorrent.sh
    prime:
      - usr/bin/qbittorrent-nox

  local:
    plugin: dump
    source: snap/local

#  deps:
#    plugin: nil
#    source: .
#    stage-packages:
#      - shared-mime-info
